services:
  - docker:dind

build:
  stage: build
  image: docker:stable
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - dev
  tags:
    - docker

rebase-customers:
  stage: build
  script:
    - apk update && apk add git && apk add bash && apk add curl
    - git remote set-url origin https://rebase:$REBASE_TOKEN@gitlab.tunex.io/dev/mobidax.git
    - bash ./rebase.sh
  only:
    - dev
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest
    - sudo sh -c "cd /root/opendax && docker-compose up -Vd mobidax"
  only:
    - dev
  tags:
    - elvira
