name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - feature_web/*
      - dev

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: web

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        # TODO: Create a PAT with `read:packages` and `write:packages` scopes and save it as an Actions secret `CR_PAT`
        run: echo "${{ secrets.CR_PAT }}" | docker login docker.pkg.github.com  -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=docker.pkg.github.com/alinetskyi/mobidax/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
      - name: Redeploy image on Stage
        run: |
          IMAGE_ID=docker.pkg.github.com/alinetskyi/mobidax/$IMAGE_NAME
          echo "${{ secrets.CR_PAT }}" | docker login docker.pkg.github.com  -u ${{ github.actor }} --password-stdin
          docker pull docker.pkg.github.com/alinetskyi/mobidax/redeploy:latest
          echo 'export WEBHOOK_JWT_SECRET=${{ secrets.WEBHOOK_JWT_SECRET }} && bundle exec rake payload:send[mobidax,$IMAGE_ID:latest,http://trade.mobidax.io:1337]' |  docker run -i -e IMAGE_ID=$IMAGE_ID -e VERSION=latest docker.pkg.github.com/alinetskyi/mobidax/redeploy:latest bash
